- name: host
  hosts: production.monprojet.com
  become: true 
  vars:
    serveur: kieran

  tasks:
  - name: create user esiee
    ansible.builtin.user:
      name: esiee
      state: present

  - name: deploy clés ssh
    ansible.posix.authorized_key:
      user: esiee
      state: present 
      key: '{{item}}'
    with_file: 
      - keys/esiee.txt

  - name: add group sudoers
    ansible.builtin.copy:
      dest: /etc/sudoers.d/esiee
      content: ' esiee ALL=(ALL) NOPASSWD :ALL '


  - name: deploy msg 
    vars:
      manga: One piece
    ansible.builtin.template:
      src: templates/motd.j2
      dest: /etc/motd